### ISSUE TITLE
leptos - tailwind - axum - cargo-leptos compatibility issue

### ISSUE THREAD

**Issue by ebadta81** [gbj/leptos#163]
Hi,

There are some incompatibilities between ```leptos_axum::render_app_to_stream``` and cargo-leptos.

render_app_to_stream use the pkg_path variable to refer to the generated wasm, js files, while cargo-leptos use constants, like:

```
const DEST: &str = "target/site/pkg/app.css";
...
let wasm_path = "target/site/pkg/app.wasm";
...
fs::write("target/site/pkg/app.js", js).await.dot()?;
```

This way you always need to use "/pkg/app" for ```RenderOptions::builder().pkg_path```.

It would be nice, if you could improve axum, actix integration to use generated.rs, or  integrate cargo-leptos to the leptos project.

**Comment by gbj** [comment]
You're correct. The development processes for `cargo-leptos` and for the Axum/Actix integrations overlapped and are slightly incompatible in this way. I understand this is being worked on in `cargo-leptos` and will be resolved in one of its upcoming updates but feel free to open an issue in the [`cargo-leptos` repo](https://github.com/akesson/cargo-leptos) or ask on Discord (link in the Readme in this repo)

**Comment by benwis** [comment]
I have pushed some changes as part of #167 that will restore functionality for non cargo-leptos users. cargo-leptos is under development, and I will adapt it again once it's ready for the work

**Comment by ankarhem** [comment]
@benwis

Still doesn't work though since cargo-leptos wants `app.wasm` and the changes changed it to `app_bg.wasm`?

**Comment by benwis** [comment]
Yes, the changes were reverted to make manual compilation with trunk and cargo run work as expected. cargo-leptos is undergoing some changes with the goal of streamlining things and allowing both to work as expected

------- Original Message -------
